package org.ppp

// TODO : We must make the
class Policy {
  String registry_number
  String registry_code
  String policy_area_PP
  String policy_subcategory
  String title
  String the_abstract
  String tags
  String country
  String state
  String county/Municipality
  String city/Metropolitan_area
  String language
  String targeted_population
  String population_affected_by_the_program
  String budget
  String funding_details
  String sponsors
  String time_between_enactment_and_funding
  String reason_for_enactment
  String problem
  String desired_outcome
  String outcomes
  String evidence_quality_
  String link_to_external_evaluation
  String link_to_policy_documents
  String link_to_other_documentation_about_the_policy
  String evaluation_based
  String date_of_enactment
  String date_of_implementation
  String date_of_closure
  String duration_of_program
  String legislative_reforms/Acts
  String total_annual_operational_costs
  String staff_costs
  String transfer_costs
  String material_costs
  String other_costs
  String implementation_team_size_number
  String stakeholders_policy_makers
  String stakeholders_congressmen
  String stakeholders_NGOs
  String stakeholders_others
  String partners
  String evidence_Strong_theory_of_change
  String process_map_available
  String implementors_available_for_comment_
  String authors
  String authors_related_work
  String link_to_authors_related_work
  String related_policies
  String released_by
  String link_to_released_entity
  String file_type
  String file_code
  String file_format
  String evaluated_by
  String link_to_evalution_entity
  String analysis_type
}
