databaseChangeLog() {
  changeSet(id: 'create-ppp-table', author: 'neodevelop') {
    createTable(tableName: 'policy') {
      column(name:"registry_number                             ", type:"varchar(255)")
      column(name:"registry_code                               ", type:"varchar(255)")
      column(name:"policy_area_PP                              ", type:"varchar(255)")
      column(name:"policy_subcategory                          ", type:"varchar(255)")
      column(name:"title                                       ", type:"varchar(255)")
      column(name:"released_by                                 ", type:"varchar(255)")
      column(name:"the_abstract                                ", type:"varchar(255)")
      column(name:"tags                                        ", type:"varchar(255)")
      column(name:"country                                     ", type:"varchar(255)")
      column(name:"state                                       ", type:"varchar(255)")
      column(name:"county/Municipality                         ", type:"varchar(255)")
      column(name:"city/Metropolitan_area                      ", type:"varchar(255)")
      column(name:"language                                    ", type:"varchar(255)")
      column(name:"targeted_population                         ", type:"varchar(255)")
      column(name:"population_affected_by_the_program          ", type:"varchar(255)")
      column(name:"budget                                      ", type:"varchar(255)")
      column(name:"funding_details                             ", type:"varchar(255)")
      column(name:"sponsor(s)                                  ", type:"varchar(255)")
      column(name:"time_between_enactment_and_funding          ", type:"varchar(255)")
      column(name:"reason_for_enactment                        ", type:"varchar(255)")
      column(name:"problem                                     ", type:"varchar(255)")
      column(name:"desired_outcome                             ", type:"varchar(255)")
      column(name:"outcomes                                    ", type:"varchar(255)")
      column(name:"evidence_quality_                           ", type:"varchar(255)")
      column(name:"link_to_external_evaluation                 ", type:"varchar(255)")
      column(name:"link_to_policy_documents                    ", type:"varchar(255)")
      column(name:"link_to_other_documentation_about_the_policy", type:"varchar(255)")
      column(name:"evaluation_based                            ", type:"varchar(255)")
      column(name:"date_of_enactment                           ", type:"varchar(255)")
      column(name:"date_of_implementation                      ", type:"varchar(255)")
      column(name:"date_of_closure                             ", type:"varchar(255)")
      column(name:"duration_of_program                         ", type:"varchar(255)")
      column(name:"legislative_reforms/Acts                    ", type:"varchar(255)")
      column(name:"total_annual_operational_costs              ", type:"varchar(255)")
      column(name:"staff_costs                                 ", type:"varchar(255)")
      column(name:"transfer_costs                              ", type:"varchar(255)")
      column(name:"material_costs                              ", type:"varchar(255)")
      column(name:"other_costs                                 ", type:"varchar(255)")
      column(name:"implementation_team_size_(number)           ", type:"varchar(255)")
      column(name:"stakeholders_policy_makers                  ", type:"varchar(255)")
      column(name:"stakeholders_congressmen                    ", type:"varchar(255)")
      column(name:"stakeholders_NGOs                           ", type:"varchar(255)")
      column(name:"stakeholders_others                         ", type:"varchar(255)")
      column(name:"partners                                    ", type:"varchar(255)")
      column(name:"evidence_Strong_theory_of_change            ", type:"varchar(255)")
      column(name:"process_map_available                       ", type:"varchar(255)")
      column(name:"implementors_available_for_comment_         ", type:"varchar(255)")
      column(name:"authors                                     ", type:"varchar(255)")
      column(name:"authors_related_work                        ", type:"varchar(255)")
      column(name:"link_to_authors_related_work                ", type:"varchar(255)")
      column(name:"related_policies                            ", type:"varchar(255)")
      column(name:"released_by                                 ", type:"varchar(255)")
      column(name:"link_to_released_entity                     ", type:"varchar(255)")
      column(name:"file_type                                   ", type:"varchar(255)")
      column(name:"file_code                                   ", type:"varchar(255)")
      column(name:"file_format                                 ", type:"varchar(255)")
      column(name:"evaluated_by                                ", type:"varchar(255)")
      column(name:"link_to_evalution_entity                    ", type:"varchar(255)")
      column(name:"analysis_type                               ", type:"varchar(255)")
    }
  }
}
